import { useState, useEffect } from 'react'

const COMPANY = 'INVESTICA AS'
const ORG = '928 926 141'
const ADDRESS = 'Helgesens gate 72, 0558 Oslo, Norway'
const UPDATED = 'June 2025'

function Section({ title, children }) {
  return (
    <div className="space-y-2">
      <h3 className="text-sm font-semibold text-white">{title}</h3>
      <div className="text-sm text-gray-400 leading-relaxed space-y-2">{children}</div>
    </div>
  )
}

function Terms() {
  return (
    <div className="space-y-6">
      <p className="text-xs text-gray-600">Last updated: {UPDATED}</p>

      <Section title="1. Service owner">
        <p>Offerlia is owned and operated by {COMPANY}, org. nr. {ORG}, {ADDRESS}.</p>
      </Section>

      <Section title="2. Acceptance of terms">
        <p>By accessing or using Offerlia ("the Service") you agree to be bound by these Terms of Use. If you do not agree, you must not use the Service.</p>
      </Section>

      <Section title="3. Description of the Service">
        <p>Offerlia is an AI-powered tool that generates job application materials — including cover letters, resume bullets, and interview preparation content — based on information you provide. All output is generated automatically by artificial intelligence.</p>
      </Section>

      <Section title="4. Use at your own risk">
        <p>Your use of the Service and any content generated by it is entirely at your own risk. You are solely responsible for reviewing, verifying, and deciding whether to use any AI-generated content. {COMPANY} does not guarantee that any generated content is accurate, complete, appropriate, or fit for any particular purpose.</p>
      </Section>

      <Section title="5. No warranty">
        <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. {COMPANY.toUpperCase()} EXPRESSLY DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
        <p>{COMPANY} does not warrant that the Service will be uninterrupted, error-free, or produce any particular outcome, including employment, interview invitations, or responses from employers.</p>
      </Section>

      <Section title="6. Limitation of liability">
        <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, {COMPANY.toUpperCase()} AND ITS DIRECTORS, EMPLOYEES, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE.</p>
        <p>This includes, without limitation: lost employment opportunities, reliance on AI-generated content, data loss, or any other commercial or personal loss, even if {COMPANY} has been advised of the possibility of such damages.</p>
      </Section>

      <Section title="7. User responsibilities">
        <p>You are responsible for:</p>
        <ul className="list-disc list-inside space-y-1 pl-2">
          <li>The accuracy of any information you submit</li>
          <li>Ensuring AI-generated content is truthful and appropriate before use</li>
          <li>Complying with the terms and policies of any job platforms or employers you interact with</li>
          <li>Complying with all applicable laws in your jurisdiction</li>
        </ul>
      </Section>

      <Section title="8. Intellectual property">
        <p>The Offerlia name, logo, and underlying technology are the property of {COMPANY}. AI-generated output produced using your input data is provided to you for personal use. {COMPANY} claims no ownership over your personal resume or job application materials.</p>
      </Section>

      <Section title="9. Changes to the Service and Terms">
        <p>{COMPANY} reserves the right to modify, suspend, or discontinue the Service at any time without notice. These Terms may be updated at any time. Continued use of the Service after changes constitutes acceptance of the revised Terms.</p>
      </Section>

      <Section title="10. Governing law">
        <p>These Terms are governed by the laws of Norway. Any disputes arising from these Terms or your use of the Service shall be subject to the exclusive jurisdiction of the courts of Oslo, Norway.</p>
      </Section>
    </div>
  )
}

function Privacy() {
  return (
    <div className="space-y-6">
      <p className="text-xs text-gray-600">Last updated: {UPDATED}</p>

      <Section title="Data controller">
        <p>{COMPANY}<br />Org. nr. {ORG}<br />{ADDRESS}</p>
      </Section>

      <Section title="What data we process">
        <p>When you use Offerlia, you may submit the following to our servers for processing:</p>
        <ul className="list-disc list-inside space-y-1 pl-2">
          <li>CV / resume content (pasted, uploaded, or imported from LinkedIn)</li>
          <li>Job descriptions (fetched from URLs or pasted manually)</li>
        </ul>
        <p>This content constitutes personal data under the GDPR and is processed solely to generate the requested application materials.</p>
      </Section>

      <Section title="How your data is used">
        <p>Your CV and job description are transmitted to third-party AI providers for processing. We do not store your CV or job descriptions on our servers after the request is completed. Analysis results may be temporarily cached for up to 1 hour to reduce processing time, after which they are automatically deleted.</p>
        <p>Your browser stores resumes and application history locally using localStorage. This data never leaves your device unless you submit a new analysis.</p>
      </Section>

      <Section title="Third-party processors">
        <p>We use the following sub-processors to deliver the Service:</p>
        <ul className="list-disc list-inside space-y-1 pl-2">
          <li><span className="text-gray-300">Groq Inc.</span> — AI model processing (groq.com/privacy)</li>
          <li><span className="text-gray-300">Anthropic PBC</span> — AI model processing, limited use (anthropic.com/privacy)</li>
          <li><span className="text-gray-300">Render Inc.</span> — Cloud hosting (render.com/privacy)</li>
        </ul>
        <p>Each processor operates under their own privacy terms and data processing agreements. By using Offerlia, you acknowledge that your CV content will be transmitted to these processors for the purpose of generating your application materials.</p>
      </Section>

      <Section title="Legal basis (GDPR Art. 6)">
        <p>We process your data on the basis of contract performance (Art. 6(1)(b) GDPR) — specifically, to provide the Service you have requested. We do not use your data for marketing, profiling, or any purpose beyond generating your requested output.</p>
      </Section>

      <Section title="Data retention">
        <p>We do not retain your CV or job description data on our servers after processing is complete. Cached results are deleted within 1 hour. Any data stored in your browser's localStorage remains on your device and under your control — you may delete it at any time by clearing your browser data.</p>
      </Section>

      <Section title="Your rights under GDPR">
        <p>As a data subject, you have the following rights:</p>
        <ul className="list-disc list-inside space-y-1 pl-2">
          <li><span className="text-gray-300">Access</span> — request a copy of your personal data we hold</li>
          <li><span className="text-gray-300">Rectification</span> — request correction of inaccurate data</li>
          <li><span className="text-gray-300">Erasure</span> — request deletion of your data ("right to be forgotten")</li>
          <li><span className="text-gray-300">Restriction</span> — request that we limit how we process your data</li>
          <li><span className="text-gray-300">Portability</span> — request your data in a machine-readable format</li>
          <li><span className="text-gray-300">Objection</span> — object to processing based on legitimate interests</li>
        </ul>
        <p>Given that we do not retain personal data server-side, most requests can be satisfied by clearing your local browser storage. For other queries, contact us at the address below.</p>
      </Section>

      <Section title="Complaints">
        <p>You have the right to lodge a complaint with the Norwegian Data Protection Authority (Datatilsynet) at datatilsynet.no if you believe your rights under GDPR have been violated.</p>
      </Section>

      <Section title="Contact">
        <p>For privacy-related enquiries, please contact {COMPANY} at:</p>
        <p>{ADDRESS}</p>
      </Section>
    </div>
  )
}

export default function LegalModal({ onClose }) {
  const [tab, setTab] = useState('terms')

  useEffect(() => {
    function onKey(e) { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [onClose])

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4">
      <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full sm:max-w-2xl bg-gray-900 border border-gray-700 rounded-t-2xl sm:rounded-2xl flex flex-col max-h-[90vh]">

        {/* Header */}
        <div className="flex items-center justify-between px-6 pt-5 pb-4 border-b border-gray-800 shrink-0">
          <div className="flex rounded-lg overflow-hidden border border-gray-700 text-xs">
            <button
              onClick={() => setTab('terms')}
              className={`px-4 py-1.5 transition-colors ${tab === 'terms' ? 'bg-violet-600 text-white' : 'bg-gray-800 text-gray-400 hover:text-white'}`}
            >
              Terms of Use
            </button>
            <button
              onClick={() => setTab('privacy')}
              className={`px-4 py-1.5 transition-colors ${tab === 'privacy' ? 'bg-violet-600 text-white' : 'bg-gray-800 text-gray-400 hover:text-white'}`}
            >
              Privacy Policy
            </button>
          </div>
          <button onClick={onClose} className="text-gray-500 hover:text-white transition-colors text-lg leading-none ml-4">✕</button>
        </div>

        {/* Content */}
        <div className="overflow-y-auto px-6 py-5 flex-1">
          {tab === 'terms' ? <Terms /> : <Privacy />}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-gray-800 shrink-0 text-xs text-gray-600 flex items-center justify-between">
          <span>{COMPANY} · Org. {ORG}</span>
          <span>{ADDRESS}</span>
        </div>
      </div>
    </div>
  )
}
